name: Update-help-menu-git-pages

on:
  workflow_run:
    workflows: 
      - Update-translations
    types:
      - completed
  workflow_dispatch:

jobs:
  generate_doc:
    name: Generates JSON files for help menu and translations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Fetch JSON data
        run: |
          python -m pip install -r .github/scripts/update-help-menu/requirements.txt
          python .github/scripts/update-help-menu/gatherHelpMenuContent.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch Branches
        run: git fetch --all

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout update-master-translations || git checkout -b update-master-translations
          git add help_menu_cache_data/
          git commit -m "Update help menu data: $(date -u)" || echo "No changes to commit"
          git push origin update-master-translations
