name: Update-help-menu-github-pages

on:
  # Trigger when the Update-translations workflow finishes
  workflow_run:
    workflows: 
      - Update-translations
    types:
      - completed
  # Allows manual run from the Actions tab
  workflow_dispatch:

jobs:
  generate_doc:
    name: Generate JSON files for help menu and translations
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - name: Install Git and SSH client
        run: apt-get update && apt-get install -y openssh-client git

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Version range or exact version
          architecture: 'x64' # optional x64 or x86. Defaults to x64
      
      - name: Generate help menu JSON files
        run: | 
          python -m pip install -r .github/scripts/update-help-menu/requirements.txt
          python .github/scripts/update-help-menu/gatherHelpMenuContent.py

      - name: Configure Git identity for commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git config --global --add safe.directory /__w/Courseplay_FS25/Courseplay_FS25

      - name: Push help menu data to CourseplayHelpFS25
        uses: cpina/github-action-push-to-another-repository@composite-1.5.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        with:
          source-directory: help_menu_cache_data/
          destination-github-username: 'Jan2903'
          destination-repository-name: 'CourseplayHelp'
          commit-message: 'Updated from Courseplay_FS25'
          target-directory: data/
          target-branch: main
